news_collecting:
  description: >
    Tìm kiếm và tóm tắt 3 bài báo có ảnh hưởng lớn nhất đến thị trường chứng khoán Việt Nam
    trong vòng 3 tháng tính đến ngày hiện tại ({current_date}).

    Quy trình thực hiện:
    1. Sử dụng công cụ `SerperDevTool` MỘT LẦN để tìm các bài báo liên quan đến tin tức vĩ mô và chính sách kinh tế Việt Nam (ví dụ: dự báo tăng trưởng, lãi suất, thuế, đầu tư công, tỉ giá hối đoái...). Ưu tiên kết quả từ các nguồn uy tín.
    2. Từ kết quả tìm kiếm, chọn 3 bài báo tiêu biểu nhất dựa trên mức độ ảnh hưởng, độ tin cậy và mức độ liên quan đến thị trường chứng khoán Việt Nam. KHÔNG chọn các bài viết từ nguồn vietstock.vn.
    3. Sử dụng công cụ `ScrapeWebsiteTool` để thu thập nội dung chi tiết của từng bài báo đã chọn. KHÔNG thu thập nội dung các bài viết từ nguồn vietstock.vn.
    4. Tóm tắt nội dung chính của từng bài trong 3–5 câu, tập trung vào tác động đến thị trường chứng khoán.

    Giới hạn:
    - Chỉ chọn bài viết có ngày đăng trong vòng 3 tháng trở lại.
    - KHÔNG lựa chọn hay sử dụng các bài viết từ nguồn vietstock.vn.
    - Chỉ chọn bài có tiêu đề và nội dung thể hiện rõ ảnh hưởng đến thị trường tài chính/chứng khoán Việt Nam.
    - KHÔNG được tự tạo ra nội dung. Câu trả lời phải dựa trên dữ liệu trích xuất từ 2 công cụ `SerperDevTool` và `ScrapeWebsiteTool`.
  expected_output: >
    Một danh sách dạng markdown gồm 3 mục, mỗi mục bao gồm:
    - Tiêu đề bài báo (in đậm)
    - Ngày đăng
    - Nguồn (kèm liên kết URL)
    - Tóm tắt 3–5 câu bằng tiếng Việt nêu rõ nội dung chính và ảnh hưởng đến thị trường

  agent: stock_news_researcher

fundamental_analysis:
  description: >
    Phân tích cơ bản mã cổ phiếu {symbol} dựa trên các chỉ số tài chính để đánh giá mức định giá và sức khỏe doanh nghiệp.

    Quy trình thực hiện:
    1. Sử dụng công cụ `fund_tool` để thu thập các chỉ số: P/E, P/B, ROE, D/E, EPS, EV/EBITDA, tăng trưởng doanh thu/lợi nhuận, và biên lợi nhuận.
    2. Xác định cổ phiếu thuộc ngành nào.
    3. So sánh P/E và P/B của cổ phiếu với trung bình ngành từ tệp `knowledge/PE_PB_industry_average.json`.
       Nếu ngành chưa có dữ liệu, sử dụng ngành gần nhất tương đương.
    4. Phân tích các chỉ số còn lại để đánh giá hiệu suất hoạt động và mức độ rủi ro tài chính.

    Ngày thực hiện: {current_date}
  expected_output: >
    Một báo cáo bằng tiếng Việt, dài 2–3 đoạn, bao gồm:
    - Nhận định định giá: rẻ / đắt / hợp lý
    - Đánh giá hiệu quả hoạt động tài chính: liệu các chỉ số nằm trong ngưỡng tốt hay không
    - Nhận xét tổng thể về triển vọng kinh doanh

  agent: fundamental_analyst

technical_analysis:
  description: >
    Đánh giá xu hướng giá của cổ phiếu {symbol} trong ngày {current_date} thông qua phân tích kỹ thuật.

    Quy trình thực hiện:
    1. Sử dụng công cụ `tech_tool` để thu thập các chỉ báo: SMA, EMA, RSI, MACD, khối lượng giao dịch, OBV và xác định vùng hỗ trợ/kháng cự.
    2. Xác định xu hướng hiện tại (tăng/giảm/tích lũy).
    3. Đưa ra đánh giá động lượng và khả năng xuất hiện tín hiệu giao dịch.

  expected_output: >
    Một báo cáo bằng tiếng Việt, dài 2–3 đoạn, bao gồm:
    - Nhận định xu hướng hiện tại (tăng/giảm/đi ngang)
    - Phân tích tín hiệu kỹ thuật (ví dụ: RSI quá mua/quá bán, giao cắt MACD...)
    - Đánh giá tổng thể về thời điểm mua bán từ góc nhìn kỹ thuật

  agent: technical_analyst

investment_decision:
  description: >
    Dựa trên kết quả tổng hợp từ các phân tích thành phần (news_collecting, fundamental_analysis, technical_analysis), 
    đánh giá mã cổ phiếu {symbol} bằng hệ thống điểm số lượng hóa và đưa ra khuyến nghị đầu tư cụ thể.

    Quy trình thực hiện:
    1. Tóm tắt ngắn gọn kết quả phân tích từng phần: vĩ mô, cơ bản, kỹ thuật.
    2. Chấm điểm từng yếu tố (thang điểm 0–10), kèm lý do.
    3. Tính điểm tổng hợp (trung bình gia quyền hoặc theo logic được mô tả).
    4. Đưa ra khuyến nghị rõ ràng: **MUA**, **GIỮ**, hoặc **BÁN**, dựa trên ngưỡng điểm như sau:
       - **MUA**: nếu điểm trung bình >= 7.5
       - **GIỮ**: nếu điểm trung bình từ 4.0 đến 7.4
       - **BÁN**: nếu điểm trung bình < 4.0
    5. Nếu chưa đạt ngưỡng **MUA** hoặc **BÁN**: đề xuất mức giá mục tiêu dựa trên phân tích kỹ thuật.

    Lưu ý:
    - **KHÔNG** được bỏ qua khuyến nghị hành động.
    - Kết luận **phải** được xây dựng trên nền tảng điểm số và phân tích từ cả 3 yếu tố.
    - Ưu tiên các khuyến nghị có thể kiểm chứng và tái sử dụng trong báo cáo phân tích đầu tư chuyên nghiệp.

  expected_output: >
    Một đoạn văn bằng tiếng Việt, có cấu trúc chuẩn như sau:
    - Tên công ty, mã cổ phiếu, ngành nghề
    - **Phân tích vĩ mô**: Tóm tắt khoảng 200 từ + điểm (0–10) + lý do
    - **Phân tích cơ bản**: Tóm tắt khoảng 200 từ + điểm (0–10) + lý do
    - **Phân tích kỹ thuật**: Tóm tắt khoảng 200 từ + điểm (0–10) + lý do
    - **Kết luận**: tính điểm trung bình (ví dụ: 7.8/10) và đưa ra khuyến nghị MUA / GIỮ / BÁN
    - **Nếu GIỮ**: đề xuất 2 mức giá mục tiêu để MUA và BÁN dựa trên phân tích kỹ thuật.

  agent: investment_strategist